'use client';

import type { SlideProps } from '../slide-renderer';
import { getMermaidRenderPriority, useMermaid } from '@/lib/use-mermaid';

export function DiagramSlide({ slide, svg }: SlideProps) {
  const mermaidSyntax = slide.diagram?.mermaidSyntax;
  const priority = getMermaidRenderPriority(svg, mermaidSyntax);
  const mermaid = useMermaid(
    priority === 'mermaid' ? mermaidSyntax : undefined,
    `mermaid-slide-${slide.slideNumber}`,
  );

  return (
    <div
      className="flex flex-col justify-center h-full px-16"
      style={{ backgroundColor: 'var(--slide-bg)', color: 'var(--slide-text)' }}
    >
      <h2 className="text-3xl font-bold mb-6" style={{ color: 'var(--slide-primary)' }}>
        {slide.title}
      </h2>

      {/* Priority 1: Pre-rendered SVG from diagrams[] */}
      {priority === 'prerendered' && svg && (
        // SVGs are server-generated by the workflow pipeline — trusted source
        <div
          className="flex-1 flex items-center justify-center overflow-hidden"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      )}

      {/* Priority 2: Client-side Mermaid rendering */}
      {priority === 'mermaid' && (
        <>
          {mermaid.loading && (
            <div className="flex-1 flex items-center justify-center text-gray-400">
              Rendering diagram...
            </div>
          )}
          {mermaid.svg && (
            <div
              className="flex-1 flex items-center justify-center overflow-hidden"
              dangerouslySetInnerHTML={{ __html: mermaid.svg }}
            />
          )}
          {mermaid.error && (
            <div className="flex-1 flex items-center justify-center">
              <div className="rounded-lg border-2 border-red-200 bg-red-50 p-6 text-center">
                <p className="text-red-600 font-medium mb-2">Diagram could not be rendered</p>
                <p className="text-sm text-gray-500">
                  {slide.diagram?.description ?? mermaid.error}
                </p>
              </div>
            </div>
          )}
        </>
      )}

      {/* Priority 3: Description text fallback */}
      {priority === 'fallback' && (
        <div className="flex-1 flex items-center justify-center text-gray-400 italic">
          {slide.diagram?.description ?? 'Diagram not available'}
        </div>
      )}

      {slide.content && (
        <p className="mt-4 text-base opacity-70">{slide.content}</p>
      )}
    </div>
  );
}
